Mining TNT v 0.1 configuration
Add item ID's sparated by spaces for them to be affected by TNT.
Example:
DestroyTheseBlocks=1 2 3 4 17
//DestroyTheseBlocks=
MaxAltitude=70
CreeperNerf=true
CreepersActLikeTNT=false
