#Minecraft server properties
#Fri Mar 20 16:06:45 UTC 2026
allow-flight=false
allow-nether=true
level-name=world
level-seed=
max-players=20
online-mode=false
pvp=true
enable-query=true
query.port=50179
server-ip=0.0.0.0
server-port=50179
spawn-animals=true
spawn-monsters=true
view-distance=10
white-list=false
